name: 'Setup Android Build Environment'
description: 'Sets up JDK and Google Services configuration for Android builds'

inputs:
  google-services-json:
    description: 'Content of google-services.json file'
    required: true

runs:
  using: 'composite'
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v4

    # Sets up a JDK on the job so that we can run Java code
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        java-package: jdk

    - name: Add Google Services from Secrets
      run: 'echo "$GOOGLE_SERVICES_JSON" > ./sample/google-services.json'
      shell: bash
      env:
        GOOGLE_SERVICES_JSON: ${{ inputs.google-services-json }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: false
