package com.klaviyo.fixtures

import android.annotation.SuppressLint
import android.content.Context
import android.content.Intent
import android.net.Uri
import com.klaviyo.analytics.Klaviyo
import com.klaviyo.analytics.model.Event
import com.klaviyo.analytics.model.EventMetric
import com.klaviyo.analytics.model.ProfileKey
import io.mockk.every
import io.mockk.mockk
import io.mockk.mockkObject
import io.mockk.mockkStatic
import io.mockk.unmockkObject
import io.mockk.unmockkStatic
import io.mockk.verify
import java.io.Serializable

/**
 * Utility class for mocking Klaviyo singleton from Java tests.
 *
 * Since Klaviyo is a Kotlin object (singleton), it can only be mocked using MockK's
 * mockkObject function, which is only available in Kotlin. This class provides a bridge
 * for Java tests to mock and verify Klaviyo method calls.
 */
@SuppressLint("StaticFieldLeak")
object KlaviyoMock {

    // Mock objects exposed for Java tests to use
    @JvmStatic
    val mockContext: Context = mockk(relaxed = true)

    @JvmStatic
    val mockIntent: Intent = mockk(relaxed = true)

    @JvmStatic
    val mockUri: Uri = mockk(relaxed = true)

    /**
     * Sets up mocks for all Klaviyo public API methods.
     * Call this in @Before setup methods.
     */
    @JvmStatic
    fun setup() {
        // Mock the static methods generated by @JvmStatic
        // mockkStatic must be called before mockkObject for proper interception of static methods
        mockkStatic(Klaviyo::class)
        mockkObject(Klaviyo)

        // Mock all public methods to return Klaviyo for chaining
        every { Klaviyo.initialize(any(), any()) } returns Klaviyo
        every { Klaviyo.registerForLifecycleCallbacks(any()) } returns Klaviyo
        every { Klaviyo.setProfile(any()) } returns Klaviyo
        every { Klaviyo.setEmail(any()) } returns Klaviyo
        every { Klaviyo.setPhoneNumber(any()) } returns Klaviyo
        every { Klaviyo.setExternalId(any()) } returns Klaviyo
        every { Klaviyo.setPushToken(any()) } returns Klaviyo
        every { Klaviyo.setProfileAttribute(any(), any()) } returns Klaviyo
        every { Klaviyo.resetProfile() } returns Klaviyo
        every { Klaviyo.createEvent(any<Event>()) } returns Klaviyo
        every { Klaviyo.createEvent(any<EventMetric>(), any()) } returns Klaviyo
        every { Klaviyo.handlePush(any()) } returns Klaviyo
        every { Klaviyo.registerDeepLinkHandler(any()) } returns Klaviyo
        every { Klaviyo.unregisterDeepLinkHandler() } returns Klaviyo

        // Mock getters to return test values
        every { Klaviyo.getEmail() } returns "test@example.com"
        every { Klaviyo.getPhoneNumber() } returns "+15555555555"
        every { Klaviyo.getExternalId() } returns "ext-123"
        every { Klaviyo.getPushToken() } returns "push-token-abc"

        // Mock boolean methods
        every { Klaviyo.handleUniversalTrackingLink(any<String>()) } returns true
        every { Klaviyo.handleUniversalTrackingLink(any<Intent>()) } returns true

        // Extension properties defined inside Klaviyo object - accessed via run block
        every { Klaviyo.run { any<Intent>().isKlaviyoIntent } } returns true
        every { Klaviyo.run { any<Intent>().isKlaviyoNotificationIntent } } returns true
        every { Klaviyo.run { any<Intent>().isKlaviyoUniversalTrackingIntent } } returns true
        every { Klaviyo.run { any<Uri>().isKlaviyoUniversalTrackingUri } } returns true

        // Static wrapper methods for the extension properties (Java-friendly)
        every { Klaviyo.isKlaviyoIntent(any()) } returns true
        every { Klaviyo.isKlaviyoNotificationIntent(any()) } returns true
        every { Klaviyo.isKlaviyoUniversalTrackingIntent(any()) } returns true
        every { Klaviyo.isKlaviyoUniversalTrackingUri(any()) } returns true

        // Mock createEvent with single param (thanks to @JvmOverloads)
        every { Klaviyo.createEvent(any<EventMetric>()) } returns Klaviyo
    }

    /**
     * Cleans up mocks.
     * Call this in @After teardown methods.
     */
    @JvmStatic
    fun teardown() {
        unmockkObject(Klaviyo)
        unmockkStatic(Klaviyo::class)
    }

    // Verification methods for Java tests

    @JvmStatic
    @JvmOverloads
    fun verifyInitializeCalled(apiKey: String, count: Int = 1) {
        verify(exactly = count) { Klaviyo.initialize(apiKey, any()) }
    }

    @JvmStatic
    @JvmOverloads
    fun verifyRegisterForLifecycleCallbacksCalled(count: Int = 1) {
        verify(exactly = count) { Klaviyo.registerForLifecycleCallbacks(any()) }
    }

    @JvmStatic
    @JvmOverloads
    fun verifySetProfileCalled(count: Int = 1) {
        verify(exactly = count) { Klaviyo.setProfile(any()) }
    }

    @JvmStatic
    @JvmOverloads
    fun verifySetEmailCalled(email: String, count: Int = 1) {
        verify(exactly = count) { Klaviyo.setEmail(email) }
    }

    @JvmStatic
    @JvmOverloads
    fun verifySetPhoneNumberCalled(phone: String, count: Int = 1) {
        verify(exactly = count) { Klaviyo.setPhoneNumber(phone) }
    }

    @JvmStatic
    @JvmOverloads
    fun verifySetExternalIdCalled(externalId: String, count: Int = 1) {
        verify(exactly = count) { Klaviyo.setExternalId(externalId) }
    }

    @JvmStatic
    @JvmOverloads
    fun verifySetPushTokenCalled(token: String, count: Int = 1) {
        verify(exactly = count) { Klaviyo.setPushToken(token) }
    }

    @JvmStatic
    @JvmOverloads
    fun verifySetProfileAttributeCalled(key: ProfileKey, value: Serializable, count: Int = 1) {
        verify(exactly = count) { Klaviyo.setProfileAttribute(key, value) }
    }

    @JvmStatic
    @JvmOverloads
    fun verifyResetProfileCalled(count: Int = 1) {
        verify(exactly = count) { Klaviyo.resetProfile() }
    }

    @JvmStatic
    @JvmOverloads
    fun verifyCreateEventCalled(count: Int = 1) {
        verify(exactly = count) { Klaviyo.createEvent(any<Event>()) }
    }

    @JvmStatic
    @JvmOverloads
    fun verifyCreateEventWithMetricCalled(metric: EventMetric, count: Int = 1) {
        verify(exactly = count) { Klaviyo.createEvent(metric, any()) }
    }

    @JvmStatic
    @JvmOverloads
    fun verifyHandlePushCalled(count: Int = 1) {
        verify(exactly = count) { Klaviyo.handlePush(any()) }
    }

    @JvmStatic
    @JvmOverloads
    fun verifyHandleUniversalTrackingLinkStringCalled(url: String, count: Int = 1) {
        verify(exactly = count) { Klaviyo.handleUniversalTrackingLink(url) }
    }

    @JvmStatic
    @JvmOverloads
    fun verifyHandleUniversalTrackingLinkIntentCalled(count: Int = 1) {
        verify(exactly = count) { Klaviyo.handleUniversalTrackingLink(any<Intent>()) }
    }

    @JvmStatic
    @JvmOverloads
    fun verifyRegisterDeepLinkHandlerCalled(count: Int = 1) {
        verify(exactly = count) { Klaviyo.registerDeepLinkHandler(any()) }
    }

    @JvmStatic
    @JvmOverloads
    fun verifyUnregisterDeepLinkHandlerCalled(count: Int = 1) {
        verify(exactly = count) { Klaviyo.unregisterDeepLinkHandler() }
    }

    @JvmStatic
    @JvmOverloads
    fun verifyIsKlaviyoIntentCalled(count: Int = 1) {
        verify(exactly = count) { Klaviyo.isKlaviyoIntent(any()) }
    }

    @JvmStatic
    @JvmOverloads
    fun verifyIsKlaviyoNotificationIntentCalled(count: Int = 1) {
        verify(exactly = count) { Klaviyo.isKlaviyoNotificationIntent(any()) }
    }

    @JvmStatic
    @JvmOverloads
    fun verifyIsKlaviyoUniversalTrackingIntentCalled(count: Int = 1) {
        verify(exactly = count) { Klaviyo.isKlaviyoUniversalTrackingIntent(any()) }
    }

    @JvmStatic
    @JvmOverloads
    fun verifyIsKlaviyoUniversalTrackingUriCalled(count: Int = 1) {
        verify(exactly = count) { Klaviyo.isKlaviyoUniversalTrackingUri(any()) }
    }
}
