name: Bug Report
description: Something isn't working as expected
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to the Klaviyo Android SDK!
        
        Before you submit your issue, please read our [contributing guidelines](https://github.com/klaviyo/klaviyo-android-sdk/blob/master/.github/CONTRIBUTING.md)
        and answer each question with as much detail as you can.
        
        > Note: incomplete issues may be de-prioritized or closed.
        
        We welcome your input! If you have any code suggestions regarding your issue, feel free to
        [submit a pull request](https://github.com/klaviyo/klaviyo-android-sdk/pulls) after creating an issue.
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have read the [contributing guidelines](https://github.com/klaviyo/klaviyo-android-sdk/blob/master/.github/CONTRIBUTING.md)
          required: true
        - label: I have determined whether this bug is also reproducible in a vanilla Android project
          required: false
        - label: If possible, I've reproduced the issue using the `master` branch or latest release of this package.
          required: false
        - label: This issue hasn't been addressed in an [existing GitHub issue](https://github.com/klaviyo/klaviyo-android-sdk/issues) or [pull request](https://github.com/klaviyo/klaviyo-android-sdk/pulls).
          required: true
  - type: textarea
    attributes:
      label: Description
      render: markdown
      description: |
        A short description of the incorrect behavior.
        
        If you think this issue has been recently introduced and did not occur in an earlier version, please note that.
        If possible, include the last version that the behavior was correct in addition to your current version.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      render: markdown
      description: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      render: markdown
      description: Describe or copy/paste the behavior you observe. Include as much detail as possible, including stack traces or screenshots if available.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      render: markdown
      description: |
        Explanation of how to reproduce the incorrect behavior.
        
        This could include an attached project or link to code that is exhibiting the issue, and/or a screen recording.
      placeholder: |
        1. ...
    validations:
      required: true
  - type: input
    attributes:
      label: The Klaviyo Android SDK version information
      description: The version of the Klaviyo Android SDK used to reproduce this issue.
      placeholder: "'1.0.0' for example, or a commit hash"
    validations:
      required: true
  - type: input
    attributes:
      label: Device Information
      description: Type of device used to reproduce the issue, please be specific
      placeholder: "'Pixel 4a 5g' or 'Nexus 5 Emulator' for example"
  - type: input
    attributes:
      label: Android Studio Version
      description: The version of Android Studio used to reproduce this issue.
      placeholder: "The version displayed from 'Android Studio 〉About Android Studio'"
  - type: input
    attributes:
      label: Android API Level
      description: The version of Android where the issue was encountered, please be specific
      placeholder: "'API Level 23' for example"
