# Workflow for running Android instrumented tests across multiple API levels
# Runs on master, release/feature branches, and PRs with specific labels

name: Android SDK Instrumented Tests

# Trigger conditions
on:
  # Run on pushes to main branches
  push:
    branches:
      - 'master'
      - 'rel/*'
      - 'feat/*'
  
  # Run on PRs when specific labels are added or when labeled PRs are updated
  pull_request:
    types: [labeled, synchronize]
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      api_level:
        description: 'Specific API level to test (optional, defaults to matrix)'
        required: false
        type: string

jobs:
  # Job to check if we should run instrumented tests on PRs
  check-pr-labels:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    outputs:
      should-run: ${{ steps.check.outputs.result }}
    steps:
      - name: Check for instrumented test labels
        id: check
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            const testLabels = ['test:instrumented', 'test:all'];
            const hasTestLabel = testLabels.some(label => labels.includes(label));
            
            console.log(`Labels: ${labels.join(', ')}`);
            console.log(`Has test label: ${hasTestLabel}`);
            
            return hasTestLabel ? 'true' : 'false';

  # Main instrumented tests job
  instrumented-tests:
    name: API ${{ matrix.api-level }} Instrumented Tests
    runs-on: ubuntu-22.04
    
    # Run if: push to branches OR PR with correct labels OR manual dispatch
    if: |
      github.event_name == 'push' || 
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && needs.check-pr-labels.outputs.should-run == 'true')
    
    needs: [check-pr-labels]
    # Allow check-pr-labels to be skipped for non-PR events
    continue-on-error: false
    
    strategy:
      fail-fast: false
      matrix:
        api-level: [23, 36]
        arch: [x86_64]
        exclude:
          # API 23 doesn't support x86_64, use x86 instead
          - api-level: 23
            arch: x86_64
        include:
          - api-level: 23
            arch: x86

    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}

      - name: Add Google Services from Secrets
        run: 'echo "$GOOGLE_SERVICES_JSON" > ./sample/google-services.json'
        shell: bash
        env:
          GOOGLE_SERVICES_JSON: ${{secrets.GOOGLE_SERVICES_JSON}}

      - name: Configure local.properties for instrumented tests
        run: |
          echo "klaviyoPublicApiKey=$INSTRUMENTED_TEST_PUBLIC_API_KEY" >> local.properties
        env:
          INSTRUMENTED_TEST_PUBLIC_API_KEY: ${{secrets.INSTRUMENTED_TEST_PUBLIC_API_KEY}}

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      # Use manual API level if specified in workflow_dispatch, otherwise use matrix
      - name: Set API Level
        id: api-setup
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ -n "${{ inputs.api_level }}" ]; then
            echo "api_level=${{ inputs.api_level }}" >> $GITHUB_OUTPUT
          else
            echo "api_level=${{ matrix.api-level }}" >> $GITHUB_OUTPUT
          fi

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ steps.api-setup.outputs.api_level }}-${{ matrix.arch }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ steps.api-setup.outputs.api_level }}
          arch: ${{ matrix.arch }}
          target: ${{ steps.api-setup.outputs.api_level >= 30 && 'google_apis' || 'default' }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: echo "Generated AVD snapshot for caching."

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ steps.api-setup.outputs.api_level }}
          arch: ${{ matrix.arch }}
          target: ${{ steps.api-setup.outputs.api_level >= 30 && 'google_apis' || 'default' }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            echo "Running instrumented tests on API ${{ steps.api-setup.outputs.api_level }}"
            ./gradlew :sample:connectedAndroidTest --stacktrace --no-daemon
            echo "Instrumented tests completed"

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-api-${{ steps.api-setup.outputs.api_level }}
          path: |
            sample/build/reports/androidTests/connected/
            sample/build/outputs/androidTest-results/
          retention-days: 7

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-api-${{ steps.api-setup.outputs.api_level }}
          path: sample/build/test-results/
          retention-days: 7

  # Summary job that provides overall status
  instrumented-tests-summary:
    name: Instrumented Tests Summary
    runs-on: ubuntu-22.04
    needs: [instrumented-tests]
    if: always() && (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && needs.check-pr-labels.outputs.should-run == 'true'))
    
    steps:
      - name: Check test results
        run: |
          if [ "${{ needs.instrumented-tests.result }}" == "success" ]; then
            echo "✅ All instrumented tests passed across API levels!"
          elif [ "${{ needs.instrumented-tests.result }}" == "failure" ]; then
            echo "❌ Some instrumented tests failed. Check the individual API level jobs for details."
            exit 1
          elif [ "${{ needs.instrumented-tests.result }}" == "cancelled" ]; then
            echo "⚠️ Instrumented tests were cancelled."
            exit 1
          else
            echo "⚠️ Instrumented tests completed with status: ${{ needs.instrumented-tests.result }}"
          fi