# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '0 13 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been inactive for 60 days, and will be closed after 7 days of inactivity.'
        stale-pr-message: 'This pull request has been inactive for 60 days, and will be closed after 7 days of inactivity.'

        close-issue-message: 'This issue has been closed due to inactivity.'
        close-pr-message: 'This pull request has been closed due to inactivity.'
        
