# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# It should run at 9am EST (if I did the UTC date math right)
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-22.04
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-issue-stale: -1
        days-before-issue-close: -1
        days-before-pr-stale: 16
        days-before-pr-close: 14
        stale-pr-message: 'This PR has not seen any updates in the last 16 days. Without further action this PR will be closed in 14 days. To disable further staleness checks add the `evergreen` label.'
        close-pr-message: 'This PR has seen no updates in the past 30 days and will now be closed. Restore the branch and create a new PR if you wish to continue work.'
        stale-pr-label: 'stale'
        exempt-pr-labels: 'evergreen'
        operations-per-run: 300
